### ISSUE TITLE
Update to Python 3

### ISSUE THREAD

**Issue by finnless** [Open-Book-Genome-Project/sequencer#25]
Article: [The key differences between Python 2.7.x and Python 3.x with examples](https://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html)

Python 2 is past end of life: [The final Python 2 release marks the end of an era](https://stackoverflow.blog/2020/04/23/the-final-python-2-release-marks-the-end-of-an-era/)

- [x] Create Task List
- [x] Python 3: DEFAULT_SEQUENCER.sequence "clean" bytes instead of string [#27](https://github.com/Open-Book-Genome-Project/sequencer/issues/27)
- [x] Python 3: DEFAULT_SEQUENCER.sequence upload bytes required #30

**Comment by cclauss** [comment]
#27 was closed in #29...

What other tasks are required here?  Can we add type hint on function parameters and return values or do we still need to be compatible with Python 2?

**Comment by finnless** [comment]
We are python 3 only!
